### ISSUE TITLE
Github configuration in .gitpod.yml being deprecated

### ISSUE THREAD

**Issue by howardyoo** [honeycombio/workshop-advanced-instrumentation#38]
# Problem
the following section in [.gitpod.yml](.gitpod.yml) is being deprecated.
```
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
```
Not sure what is the alternative, but it is apparent that these settings will not be supported in near future.
